version: '3.8'

services:
  order-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-app
    depends_on:
      - order-db
    env_file:
      - .env
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
    networks:
      - shared-network

  order-db:
    image: postgres:17
    container_name: order-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network

volumes:
  pgdata:

networks:
  shared-network:
    external: true